### ISSUE TITLE
Add code coverage badge

### ISSUE THREAD

**Issue by ntdef** [uptake/cran-server#12]
Need to get a code coverage badge on here.

**Comment by ntdef** [comment]
@jameslamb do you know how to add organization repos to coveralls? When I tried to cran-server, it was only showing repos that I own under my personal account.

**Comment by jameslamb** [comment]
@ntdef we've used codecov for other projects, but should be able to add coveralls! I'm an admin on `UptakeOpenSource` so maybe I can set it up? Remind me tomorrow and we can talk to infra people at Uptake about what the best ownership strategy is.

But TL;DR let's do it

**Comment by ntdef** [comment]
Let's use codecov then. Do you know how to set it up?

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
