### ISSUE TITLE
Archive and support devtools::install_version

### ISSUE THREAD

**Issue by ngparas** [uptake/cran-server#15]
Consider support for installing old versions of packages with devtools: https://github.com/r-lib/devtools/blob/master/R/install-version.r#L45

Currently the only way to do it is to go to the path directly,
```
install.packages("http://cran.mycompany.com/src/contrib/mypackage_0.3.2.tar.gz", repos = NULL)
```

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
