### ISSUE TITLE
Push docker image to https://hub.docker.com/

### ISSUE THREAD

**Issue by peterableda** [uptake/cran-server#23]

**Comment by ntdef** [comment]
Hi @peterableda! Thanks for posting this. It's definitely something I had on my backlog. Right now Uptake doesn't have an open source account on DockerHub, but we'll have one shortly and post the image there.

**Comment by ntdef** [comment]
@jameslamb were you able to look into this?

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
