### ISSUE TITLE
Copy fileobj into member buffer when creating `Package`

### ISSUE THREAD

**Issue by ngparas** [uptake/cran-server#27]
Because the fileobj isn't copied into a buffer local to the Package instance we require resets outside of the class e.g. https://github.com/UptakeOpenSource/cran-server/blob/master/cranserver/server.py#L88

The constructor should copy the fileobj into a new BytesIO

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
