### ISSUE TITLE
Add extension system for supporting other backends

### ISSUE THREAD

**Issue by ntdef** [uptake/cran-server#33]
The code is modular enough to support other backends, but to swap out a backend you would actually have to modify the codebase as-is. Ideally, you should be able to point to point to a Python class at startup and use that as the storage backend. 

It's probably worthwhile to look into how Flask/Gunicorn does this when looking for the `app` object.

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
