### ISSUE TITLE
Add support authentication and roles

### ISSUE THREAD

**Issue by ntdef** [uptake/cran-server#43]
Add support for authentication and roles. As a added bonus, it would be nice if we could support OAuth if possible. 

Issue #9 is dependent on this.

**Comment by ntdef** [comment]
Here's a nice tutorial https://blog.miguelgrinberg.com/post/oauth-authentication-with-flask

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
