### ISSUE TITLE
Local FS Concurrency

### ISSUE THREAD

**Issue by ngparas** [uptake/cran-server#47]
The default configuration (local filesystem) used in the quickstart can have inconsistent behavior when installing packages from R.

Following the instructions in the quickstart, I uploaded `httr` version `1.3.1` to test installs. I can start an R session and run

```
> install.packages('httr', repos = c('http://localhost:8080'))
```

and it will either succeed or fail out after not finding the bin/macosx PACKAGES file seemingly randomly.

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
