### ISSUE TITLE
Add support for binary packages

### ISSUE THREAD

**Issue by ntdef** [uptake/cran-server#6]
Right now this project only supports packages stored under `/src/`. To offer a full featured CRAN repo we need to support binary packages. 

I don't have a Windows environment to test with but we should procure one.

**Comment by jameslamb** [comment]
I think there are Windows AMIs that are free

I think.

**Comment by jameslamb** [comment]
I think there are Windows AMIs that are free

I think.

**Comment by ntdef** [comment]
Travis just added support for Windows https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
