### ISSUE TITLE
Add a /delete route

### ISSUE THREAD

**Issue by ngparas** [uptake/cran-server#9]
Consider adding a /delete route to the server. Currently the only way to remove packages is to manually edit the PACKAGES file and manually remove the artifact from s3/the file system.

**Comment by ntdef** [comment]
This is _probably_ blocked by adding user handling right? You would want to be able to control who can issue a `/delete` command.

**Comment by bburns632** [comment]
Thank you for your interest. However, this project will be archived shortly. More details in #77 .
